{{- with .Values.secretVolume }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-volume
type: Opaque
data:
  {{- range $key, $value := . }}
  {{ $key }}: {{ $value }}
  {{- end }}
{{- end }}
