{{- with .Values.secretEnv }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-env
type: Opaque
data:
  {{- range $key, $value := . }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- end }}
