{{- if .and .Values.infra.serviceAccount.enabled .Values.infra.s3Bucket.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cron.serviceAccountName" . }}
  labels:
    {{- include "cron.labels" . | nindent 4 }}
  {{- with .Values.infra.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.infra.serviceAccount.automountServiceAccountToken }}
{{- end -}}
