{{- if .Values.global.serviceAccount.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cron.serviceAccountName" . }}
  labels:
    {{- include "cron.labels" . | nindent 4 }}
  {{- with include "cron.serviceAccountAnnotations" . }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.global.serviceAccount.automountServiceAccountToken }}
{{- end -}}
