# -- Postgres database configuration. Leave as null for no database.
postgres:
  # -- The database's name.
  name: ""
  # -- The instance size. Options: micro, small, medium, large or xlarge.
  size: null
  # -- The postgres version to use. Options: 16.2, 15.6 or 14.11
  version: null
  multiAz: null
