apiVersion: v2
name: app
description: A Helm "monochart" for deploying common application patterns

type: application

version: 0.19.2

appVersion: 0.19.2

keywords:
  - app
  - infra

dependencies:
  - name: infra
    version: 0.17.0
    repository: https://portswigger-apps.github.io/helm-charts/