apiVersion: v2
name: app
description: A Helm "monochart" for deploying common application patterns

type: application

version: 0.4.6

appVersion: 0.4.6

keywords:
  - app
  - infra

dependencies:
  - name: infra
    version: 0.1.3
    repository: https://portswigger-apps.github.io/helm-charts/
