{{- if .Values.redis.enabled -}}
{{- $secretName := printf "%s-redis-credentials" (include "infra.name" .) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "infra.labels" . | nindent 8 }}
data:
  password: {{ include "infra.fetchOrCreateSecretField" (list . $secretName "password") }}
{{- end -}}