{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "infra.name" . }}-redis-credentials
  labels:
    {{- include "infra.labels" . | nindent 8 }}
data:
   password: {{ .Values.redis.password | b64enc }}
{{- end -}}