{{- if .Values.deployment.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "app.name" . }}
  labels:
  {{- include "app.labels" . | nindent 4 }}
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      {{- include "app.labelselector" . | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 25%
  minReadySeconds: 5
    {{ $ctx := dict "includePorts" true
                  "includeProbes" true
                  "useValuesArgs" true
  }}
  {{ $ctx = merge $ctx . }}
  template: {{ template "app.podTemplate" $ctx }}
  {{- end -}}
