{{- define "app.probeConfiguration" }}
startupProbe:
  httpGet:
    path: {{ .Values.healthcheckEndpoint.path }}
    port: {{ .Values.healthcheckEndpoint.port }}
    scheme: HTTP
  failureThreshold: 60
  periodSeconds: 5
  timeoutSeconds: 2
readinessProbe:
  httpGet:
    path: {{ .Values.healthcheckEndpoint.path }}
    port: {{ .Values.healthcheckEndpoint.port }}
    scheme: HTTP
  failureThreshold: 1
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 2
livenessProbe:
  httpGet:
    path: {{ .Values.healthcheckEndpoint.path }}
    port: {{ .Values.healthcheckEndpoint.port }}
    scheme: HTTP
  failureThreshold: 3
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 2
{{- end }}

{{- define "app.portConfiguration"}}
ports:
{{- range $portName, $portSpec := .Values.ports }}
  - name: {{ $portName }}
    containerPort: {{ $portSpec.port }}
    protocol: {{ $portSpec.protocol }}
{{- end }}
{{- end }}

{{- if .Values.deployment.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "app.name" . }}
  labels:
  {{- include "app.labels" . | nindent 4 }}
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      {{- include "app.labelselector" . | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 25%
  minReadySeconds: 5
  template: {{ template "app.podTemplate" . }}
  {{- end -}}
