{{- if .Values.infra.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "app.name" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
  {{- with .Values.infra.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
    {{- if $.Values.infra.cloudfront.headerAuth.enabled }}
    traefik.ingress.kubernetes.io/router.middlewares: {{ $.Release.Name }}-cloudfront-auth@kubernetescrd }}
    {{- end }}
  {{- end }}
spec:
  {{- if .Values.infra.ingress.className }}
  ingressClassName: {{ .Values.infra.ingress.className }}
  {{- end }}
  rules:
  - {{ if .Values.infra.ingress.host -}}
    host: {{ .Values.infra.ingress.host }}
    {{- else }}
    {{- fail "ERROR: A unique hostname must be set if creating an ingress" -}}
    {{- end }}
    http:
      paths:
      {{- range $portName, $portSpec := .Values.ports }}
      {{- if $portSpec.expose }}
      {{- range $.Values.infra.ingress.paths }}
      - path: {{ . }}
        pathType: Prefix
        backend:
          service:
            name: {{ include "app.name" $ }}
            port:
              number: {{ $portSpec.port }}
      {{- end }}
      {{- end }}
      {{- end }}
{{- end -}}
