{{- if .Values.global.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "app.name" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
  {{- with include "app.ingressAnnotations" . }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.global.ingress.className }}
  ingressClassName: {{ .Values.global.ingress.className }}
  {{- end }}
  rules:
  - host: {{ required "A unique hostname must be set if creating an ingress" .Values.global.ingress.host }}
    http:
      paths:
      {{- $_ := required "A port named \"app-port\" MUST exist and MUST be exposed" (ternary "exposed" "" (get .Values.ports "app-port").expose) }}
      {{- range .Values.global.ingress.paths }}
      - path: {{ . }}
        pathType: Prefix
        backend:
          service:
            name: {{ include "app.name" $ }}
            port:
              number: {{ (get $.Values.ports "app-port").port }}
      {{- end }}
  {{- range .Values.global.ingress.extraHosts }}
  - host: {{ . }}
    http:
      paths:
      {{- $_ := required "A port named \"app-port\" MUST exist and MUST be exposed" (ternary "exposed" "" (get $.Values.ports "app-port").expose) }}
      {{- range $.Values.global.ingress.paths }}
      - path: {{ . }}
        pathType: Prefix
        backend:
          service:
            name: {{ include "app.name" $ }}
            port:
              number: {{ (get $.Values.ports "app-port").port }}
      {{- end }}
  {{- end }}
{{- end -}}
