{{- if .Values.serviceAccount.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "app.serviceAccountName" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
  {{- if or .Values.infra.aws.accountId .Values.serviceAccount.annotations}}
  annotations:
    {{- if .Values.serviceAccount.annotations }}
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
    {{- end }}
    {{- if .Values.infra.aws.accountId }}
    eks.amazonaws.com/role-arn: arn:aws:iam::{{- .Values.infra.aws.accountId }}:role/{{ include "app.serviceAccountName" . }}
    {{- end }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end -}}
