{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.name" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  selector:
    {{- include "app.labelselector" . | nindent 4 }}
  ports:
  {{- range $portName, $portSpec := .Values.ports }}
  {{- if $portSpec.expose }}
  - port: {{ $portSpec.port }}
    targetPort: {{ $portName }}
    protocol: {{ $portSpec.protocol }}
  {{- end }}
  {{- end }}
{{- end -}}
