{{- if .Values.metricsEndpoint.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ template "app.name" . }}
spec:
  jobLabel: {{ .Release.Namespace }}-{{ template "app.name" . }}
  namespaceSelector:
    matchNames:
    -  {{ .Release.Namespace }}
  podMetricsEndpoints:
  - interval: {{ .Values.metricsEndpoint.interval }}
    path: {{ .Values.metricsEndpoint.path }}
    port: {{ .Values.metricsEndpoint.port }}
    honorLabels: {{ .Values.metricsEndpoint.honorLabels }}
  podTargetLabels:
  - app.kubernetes.io/app
  - app.kubernetes.io/version
  selector:
    matchLabels:
      {{- include "app.labelselector" . | nindent 6 }}
{{- end }}