{{- if .Values.preDeployCommand }}
{{- $ctx := merge (dict "JobCommand" .Values.preDeployCommand) $ }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "app.name" . }}-pre-deploy-hook
  labels:
  {{- include "app.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template: {{ template "app.hookPodTemplate" $ctx }}
{{- end }}
