{{- if .Values.cloudfrontrouter.enabled }}

apiVersion: platform.portswigger.io/v1alpha1
kind: CloudFrontRouter
metadata:
  name: {{ include "infra.aws.name" . }}
  labels:
    {{- include "infra.labels" . | nindent 8 }}
spec:
  domainName: {{ .Values.cloudfrontrouter.domainName | quote }}
  acmCertificateARN: {{ .Values.cloudfrontrouter.acmCertificateARN | quote }}
  origins: {{ .Values.cloudfrontrouter.origins | toYaml | nindent 4 }}
  {{- with .Values.cloudfrontrouter.paths }}
  paths:
  {{- range $it := . }}
  {{- $pathPattern := $it.pathPattern }}
  {{- $cachePolicy :=  (default "CachingDisabled" $it.cachePolicy) }}
  {{- $cachePolicyId :=  (default (include "infra.cloudfrontRouter.cachePolicyId" $cachePolicy) $it.cachePolicyId) }}
  {{- $targetOrigin := $it.targetOrigin }}
  - pathPattern: {{ $pathPattern }}
    targetOrigin: {{ $targetOrigin }}
    cachePolicy: {{ $cachePolicy }}
    cachePolicyId: {{ $cachePolicyId }}
  {{- end }}
  {{- end }}
  default:
    cachePolicy: {{ .Values.cloudfrontrouter.default.cachePolicy }}
    cachePolicyId: {{ default (include "infra.cloudfrontRouter.cachePolicyId" .Values.cloudfrontrouter.default.cachePolicy ) .Values.cloudfrontrouter.default.cachePolicyId }}
    targetDomain: {{ .Values.cloudfrontrouter.default.targetDomain }}
{{- end -}}
