{{- if .Values.cloudfront.enabled }}
apiVersion: platform.portswigger.io/v1alpha1
kind: CloudFrontSite
metadata:
  name: {{ include "infra.name" . }}
  labels:
    {{- include "infra.labels" . | nindent 8 }}
spec:
  geoRestriction: {{ .Values.cloudfront.geoRestriction | toYaml | nindent 4 }}
  targetOriginDomainName: {{ default .Values.cloudfront.targetOriginDomainName .Values.global.ingress.host }}
  domainName: {{ .Values.cloudfront.domainName }}
  hostedZoneId: {{ .Values.cloudfront.hostedZoneId }}
{{- end -}}
