{{- if .Values.dynamodb.create }}
{{- $tableNames := dict }}
{{- range $item := .Values.dynamodb.tables}}
  {{- if hasKey $tableNames (required "Table name is required" $item.name) }}
    {{ fail "Table names must be unique"}}
  {{ else }}
    {{- $tableNames := set $tableNames $item.name "true" }}
  {{- end }}
{{- end }}

{{- range $table := .Values.dynamodb.tables }}
apiVersion: platform.portswigger.io/v1alpha1
kind: DynamoDBTable
metadata:
  name: {{ default (include "infra.aws.name" $) $.Values.dynamodb.prefixOverride }}-{{ $table.name }}
  labels:
    {{- include "infra.labels" $ | nindent 8 }}
spec:
  {{- $namedAttributes := dict }}
  {{- $usedAttributes := dict }}
  {{- $types := dict
    "string" "S"
    "binary" "B"
    "number" "N"
  }}
  pointInTimeRecovery: {{ $table.pointInTimeRecovery | default false }}
  attributes:
  {{- range $attribute := $table.attributes }}
    - name: {{ required "A name is required for every DynamoDB attribute you create" $attribute.name | quote }}
    {{- if hasKey $types (lower $attribute.type) }}
      type: {{ get $types (lower $attribute.type) | quote }}
    {{- else }}
      {{ fail "Attribute type must be string, binary, or number"}}
    {{- end }}
    {{- $namedAttributes := set $namedAttributes $attribute.name "true"}}
  {{- else }}
    {{ fail "At least one attribute must be set for the partition key when creating a DynamoDB table" }}
  {{- end }}
  partitionKey: {{ required "A partition key must be set if creating a DynamoDB table" $table.partitionKey | quote }}
  {{- if hasKey $namedAttributes $table.partitionKey }}
    {{- $usedAttributes := set $usedAttributes $table.partitionKey "true" -}}
  {{- else }}
    {{ fail "Any indexed attributes must be defined as attributes" }}
  {{- end}}
  {{- with $table.sortKey }}
  {{- if eq . $table.partitionKey }}
    {{- fail "The sort key cannot be the same as the partition key" }}
  {{- end }}
  sortKey: {{ . | quote }}
  {{- if hasKey $namedAttributes . }}
    {{- $usedAttributes := set $usedAttributes . "true" -}}
  {{- else }}
    {{ fail "Any indexed attributes must be defined as attributes" }}
  {{- end }}
  {{- end }}
  {{- with $table.gsis }}
  gsis:
  {{- range $gsi := . }}
    - partitionKey: {{ required "A partition key must be set for every GSI" $gsi.partitionKey | quote }}
      sortKey: {{ required "A sort key must be set for every GSI" $gsi.sortKey | quote }}
    {{- if and (hasKey $namedAttributes $gsi.partitionKey) (hasKey $namedAttributes $gsi.sortKey) }}
      {{- $usedAttributes := set (set $usedAttributes $gsi.partitionKey "true") $gsi.sortKey "true" -}}
    {{- else }}
      {{ fail "Any indexed attributes must be defined as attributes" }}
    {{- end }}
  {{- end }}
  {{- end }}
  {{- with $table.lsis }}
  {{- range $lsi := . }}
  lsis:
    {{- if not $table.sortKey }}
      {{- fail "Cannot have an LSI without a sortKey" }}
    {{- end }}
    - {{ required "A sort key must be set for every LSI" $lsi | quote }}
    {{- if hasKey $namedAttributes . }}
      {{- $usedAttributes := set $usedAttributes . "true" -}}
    {{- else }}
      {{ fail "Any indexed attributes must be defined as attributes" }}
    {{- end }}
  {{- end }}
  {{- end }}
  {{- if ne (len (keys $usedAttributes | uniq)) (len (keys $namedAttributes | uniq)) }}
    {{ fail "All attributes must be used" }}
  {{- end }}
---
{{- end }}
{{- else }}
{{- if and (not .Values.dynamodb.prefixOverride) (not (empty .Values.dynamodb.tables)) }}
  {{- fail "prefixOverride is required if create is false" }}
{{- end }}
{{- end }}