{{- if or (and .Values.s3Bucket.enabled .Values.s3Bucket.create) .Values.bedrock.enabled .Values.eventbridge.enabled }}
apiVersion: platform.portswigger.io/v1alpha1
kind: IrsaRole
metadata:
  name: {{ default ( include "infra.aws.name" . ) .Values.global.serviceAccount.name }}
  labels:
    {{- include "infra.labels" . | nindent 8 }}
spec:
  serviceAccountName: {{ default ( include "infra.name" . ) .Values.global.serviceAccount.name }}
{{- end }}
