{{ if .Values.s3Bucket.name }}
apiVersion: platform.portswigger.io/v1alpha1
kind: IrsaRole
metadata:
  name: {{ .Values.serviceAccountName }}
  labels:
    {{- include "infra.labels" . | nindent 4 }}
spec:
  {{ if .Values.serviceAccountName }}
  serviceAccountName: {{ .Values.serviceAccountName }}
  {{- else }}
  {{- fail "ERROR: A service account name must be specified when using S3 buckets" -}}
  {{- end }}
{{- end }}
