{{- if .Values.postgres.name }}
apiVersion: platform.portswigger.io/v1alpha1
kind: PostgresInstance
metadata:
    name: {{ .Values.postgres.name }}
    labels:
    {{- include "infra.labels" . | nindent 8 }}
spec:
    multiAZ: {{ .Values.postgres.multiAz }}
    size: {{ .Values.postgres.size }}
    version: {{ quote .Values.postgres.version }}
{{- end }}
