{{- if and .Values.postgres.enabled .Values.postgres.create }}
apiVersion: platform.portswigger.io/v1alpha1
kind: PostgresInstance
metadata:
    name: {{ default ( include "infra.name" . ) .Values.postgres.nameOverride }}
    labels:
    {{- include "infra.labels" . | nindent 8 }}
spec:
    multiAZ: {{ .Values.postgres.multiAz }}
    size: {{ .Values.postgres.size }}
    version: {{ quote .Values.postgres.version }}
    enablePerformanceInsights: {{ .Values.postgres.enablePerformanceInsights }}
{{- end }}
