{{- if .Values.redis.enabled }}
{{- $secretName := printf "%s-redis-credentials" (include "infra.aws.name" .) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "infra.labels" . | nindent 8 }}
data:
  password: {{ include "infra.fetchOrCreateSecretField" (list . $secretName "password") }}

---

apiVersion: platform.portswigger.io/v1alpha1
kind: RedisCluster
metadata:
  name: {{ include "infra.aws.name" . }}
  labels:
    {{- include "infra.labels" . | nindent 8 }}
spec:
  size: {{ .Values.redis.size }}
  version: {{ .Values.redis.version | quote }}
  passwordsSecretRef:
    key: password
    name: {{ $secretName }}
    namespace: {{ .Release.Namespace }}
{{- end -}}
