{{- if .Values.s3Bucket.name }}
apiVersion: platform.portswigger.io/v1alpha1
kind: S3Bucket
metadata:
    name: {{ .Values.s3Bucket.name }}
    labels:
    {{- include "infra.labels" . | nindent 4 }}
spec:
   irsaRoleName: {{ .Values.serviceAccountName }}-irsarole
   lifecycleRules: {{ toYaml .Values.s3Bucket.lifecycleRules | nindent 4 }}
{{- end }}
