{{- if and .Values.s3Bucket.enabled .Values.s3Bucket.create }}

apiVersion: platform.portswigger.io/v1alpha1
kind: S3Bucket
metadata:
  name: {{ default ( include "infra.aws.name" . ) .Values.s3Bucket.nameOverride }}
  labels:
    {{- include "infra.labels" . | nindent 8 }}
spec:
  irsaRoleName: {{ default ( include "infra.aws.name" . ) .Values.global.serviceAccount.name }}-irsarole
  dataInsightsAccess: {{if .Values.s3Bucket.enableDataInsights}}Allow{{else}}Deny{{end}}
  {{- with .Values.s3Bucket.lifecycleRules }}
  lifecycleRules:
  {{- range $i, $rule := . }}
  - {{- toYaml $rule | nindent 4}}
    {{- if not (hasKey $rule "id")}}
    id: rule-{{- $i }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}