image:
  # -- The container image of your application
  name: "public.ecr.aws/nginx/nginx"
  # -- The container tag that will be run
  tag: "alpine"

cron:
  # -- Cron formatted schedule for job.
  schedule: "* * * * *"
  # -- One of: Allow, Forbid and Replace.
  # -- Allow - allows concurrently running cron jobs.
  # -- Forbid - No concurrent runs, if last cron job hasn't finished then skip the new run
  # -- Replace - Replace the currently running cron job with a new instance.
  concurrencyPolicy: Allow
  # -- Number of retries on failure of job
  retries: 0
  # -- Number of pods of the cron job to start
  parallelism: 1
  # -- (string[]) Command to run on the image. e.g [/bin/bash, my-script.sh]
  command: null
  # -- (string[]) Arguments for the command
  args: null
  # -- One of: Never or OnFailure. Never - does not restart. OnFailure - will re-run the job if it fails
  restartPolicy: OnFailure
  # -- (int) The maximum amount of time the job should run for in seconds.
  timeoutSeconds: null

# -- List of environment variables for job container.
env: {}
  # KEY: value

# -- Secret values that are mounted as environment variables. Formatted as ```<environment variable name>: <plain text value>```
secretEnv: {}
  # secret_key: secret_value

# -- Secret values that are mounted as a file to /secrets. Formatted as ```<file name>: <base64 encoded value>```
secretVolume: {}
  # file-name.txt: aGVsbG8gMTIz

pod:
  annotations: {}

resources:
  # -- Requested CPU time for the pod
  cpu: "100m"
  # -- Maximum memory usage for the pod
  memory: "64Mi"

# -- Configuration for infra
infra:
  postgres:
    # -- (string) The database name. Must be the same as the name specified in the infra chart.
    name: null

# -- Service account configuration. Configuration is required for accessing AWS resources
serviceAccount:
  enabled: true
  # -- If the service account token should be mounted into pods that use the service account
  automountServiceAccountToken: false
  annotations: {}
  # eks.amazonaws.com/role-arn: arn:aws:iam::111122223333:role/my-role
