image:
  # -- The container image of your application
  name: "public.ecr.aws/nginx/nginx"
  # -- The container tag that will be run
  tag: "alpine"

cron:
  # -- Cron formatted schedule for job.
  schedule: "* * * * *"
  # -- One of: Allow, Forbid and Replace.
  # Allow - allows concurrently running cron jobs.
  # Forbid - No concurrent runs, if last cron job hasn't finished then skip the new run
  # Replace - Replace the currently running cron job with a new instance.
  concurrencyPolicy: Allow
  # -- Number of retries on failure of job
  retries: 0
  # -- Number of pods of the cron job to start
  parallelism: 1
  # -- (string[]) Command to run on the image. e.g [/bin/bash, my-script.sh]
  command: null
  # -- (string[]) Arguments for the command
  args: null
  # -- One of: Never or OnFailure. Never - does not restart. OnFailure - will re-run the job if it fails
  restartPolicy: OnFailure
  # -- (int) The maximum amount of time the job should run for in seconds.
  timeoutSeconds: null

# -- List of environment variables for job container.
env: {}
  # KEY: value

# -- Secret values that are mounted as environment variables. Formatted as ```<environment variable name>: <plain text value>```
secretEnv: {}
  # secret_key: secret_value

# -- Secret values that are mounted as a file to /secrets. Formatted as ```<file name>: <base64 encoded value>```
secretVolume: {}
  # file-name.txt: aGVsbG8gMTIz

pod:
  annotations: {}

resources:
  # -- Requested CPU time for the pod
  cpu: "100m"
  # -- Maximum memory usage for the pod
  memory: "64Mi"

# -- Configuration for infra
infra:
  # -- Postgres database configuration. Leave as null for no database.
  postgres:
    # -- The database's name.
    name: ""
    # -- The instance size. Options: micro, small, medium, large or xlarge.
    size: null
    # -- The postgres version to use. Options: 16.2, 15.6 or 14.11
    version: null
    # -- If database should be a multi-az deployment
    multiAz: null

  # -- S3 Bucket configuration. Set to null for no s3 bucket.
  s3Bucket:
    # -- Name of the bucket
    name: ""
    # -- Lifecycle rules. See docs at https://marketplace.upbound.io/providers/upbound/provider-aws-s3/v1.2.1/resources/s3.aws.upbound.io/BucketLifecycleConfiguration/v1beta1#doc:spec-forProvider-rule
    # The status field is required on the rule object.
    lifecycleRules:
      - expiration:
          - days: 0
        status: Disabled

  # -- Service account configuration. Configuration is required for accessing AWS resources
  serviceAccount:
    enabled: true
    name: ""
    # -- If the service account token should be mounted into pods that use the service account
    automountServiceAccountToken: false
    annotations: {}
    # eks.amazonaws.com/role-arn: arn:aws:iam::111122223333:role/my-role
