{{- if and .Values.infra.cloudfront.enabled .Values.infra.cloudfront.originHeaderAuth }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Release.Name }}-cloudfront-auth
spec:
  plugin:
    bouncer:
      headers:
        - header:
          name: X-Cloudfront-Auth
          values:
            - {{ .Values.global.ingress.host | sha256sum }}
          matchtype: one
{{- end }}
