{{- if and .Values.global.ingress.enabled (eq .Values.global.ingress.className "traefik") }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Release.Name }}-chain
spec:
  chain:
    middlewares:
    - name: {{.Release.Namespace}}-{{ .Release.Name }}-https@kubernetescrd
{{- if and .Values.infra.cloudfront.enabled .Values.infra.cloudfront.originHeaderAuth }}
    - name: {{.Release.Namespace}}-{{ .Release.Name }}-cloudfront-auth@kubernetescrd
{{- end }}
{{- end }}