{{- if and .Values.global.ingress.enabled (eq .Values.global.ingress.className "traefik") }}
{{- if .Values.global.ingress.stripPrefixes }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Release.Name }}-strip-prefixes
spec:
  stripPrefix:
    prefixes:
    {{ .Values.global.ingress.stripPrefixes | toYaml | nindent 4}}
{{- end }}
{{- end }}