{{- if and .Values.global.ingress.enabled (eq .Values.global.ingress.className "traefik") }}
{{- if and .Values.infra.cloudfront.enabled .Values.infra.cloudfront.originHeaderAuth }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Release.Name }}-cloudfront-auth
spec:
  plugin:
    checkheaders:
      headers:
        - name: X-Cloudfront-Auth
          values:
            - {{ printf "%s-%s" .Values.infra.cloudfront.hostedZoneId .Values.global.ingress.host | sha256sum }}
          matchtype: one
{{- end }}
{{- end }}