{{- if and .Values.global.ingress.enabled (eq .Values.global.ingress.className "traefik") }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Release.Name }}-chain
spec:
  chain:
    middlewares:
{{- if not (has "0.0.0.0/0" .Values.global.ingress.ipAllowListCIDRs) }}
{{- if .Values.infra.cloudfront.enabled }}
    - name: {{.Release.Namespace}}-{{ .Release.Name }}-cloudfrontgate@kubernetescrd
{{- else }}
    - name: {{.Release.Namespace}}-{{ .Release.Name }}-ipallowlist@kubernetescrd
{{- end }}
{{- end }}
{{- if and .Values.infra.cloudfront.enabled .Values.infra.cloudfront.originHeaderAuth }}
    - name: {{.Release.Namespace}}-{{ .Release.Name }}-cloudfront-auth@kubernetescrd
{{- end }}
    - name: {{.Release.Namespace}}-{{ .Release.Name }}-https@kubernetescrd
    - name: {{.Release.Namespace}}-{{ .Release.Name }}-headers@kubernetescrd
{{- if and .Values.global.ingress.authentication.enabled}}
    - name: {{.Release.Namespace}}-{{ .Release.Name }}-redirect-auth@kubernetescrd
    - name: {{.Release.Namespace}}-{{ .Release.Name }}-forward-auth@kubernetescrd
{{- end }}
{{- end }}