{{- if and .Values.global.ingress.enabled (eq .Values.global.ingress.className "traefik") }}
{{- if and .Values.global.ingress.authentication.enabled .Values.infra.cloudfront.enabled }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{.Release.Namespace}}-{{ .Release.Name }}-forward-auth
spec:
  forwardAuth:
    address: http://platform-oauth2-proxy.platform:4180/oauth2/auth
    trustForwardHeader: true
{{- end }}
{{- end }}