{{- if and .Values.global.ingress.enabled (eq .Values.global.ingress.className "traefik") }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Release.Name }}-ipallowlist
spec:
  ipAllowList:
    sourceRange:
{{- range .Values.global.ingress.ipAllowListCIDRs }}
    - {{ . }}
{{- end }}
{{- if not (has "0.0.0.0/0" .Values.global.ingress.ipAllowListCIDRs) }}
{{- if .Values.global.ingress.allowFromOffice }}
    {{- toYaml .Values.global.ingress.allowFromOfficeCIDRs | nindent 4 }}
{{- end }}
{{- if .Values.infra.cloudfront.enabled }}
    {{- toYaml .Values.global.ingress.allowFromCloudFrontCIDRs | nindent 4 }}
{{- end }}
{{- end }}
{{- end }}